pipeline {
    agent any
    
    tools {
        python '3.11' // specify the Python version to use
    }
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Test') {
            steps {
                sh 'cd ChoreShareMongoDB && pip install -r requirements.txt && -m pytest'
            }
        }

        stage('Deploy') {
            steps {
                sh 'cd ChoreShareMongoDB && pip install -r requirements.txt && python app.py'
            }
            post {
                always {
                    archiveArtifacts 'ChoreShareMongoDB/*.py'
                }
            }
        }
    }

    post {
        always {
            deleteDir()
        }
    }
}
