pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Test') {
            steps {
                sh '''
                    cd ChoreShareMongoDB
                    pip install -r requirements.txt
                    python -m pytest
                '''
            }
        }
        stage('Deploy') {
            steps {
                sh 'cd ChoreShareMongoDB && pip install -r requirements.txt && start /b python app.py'
            }
            post {
                always {
                    archiveArtifacts 'ChoreShareMongoDB/*.py'
                }
            }
        }
    }

    post {
        always {
            deleteDir()
        }
    }
}
